import  SideBar  from '@/components/layouts/Sidebar';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layouts/Header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className=''>
            -1
            <div className=''>
              --2
              <div className=''>
                ---3
                  <div className=''>
                    <SideBar/>
                  </div>
                  <div className=''>
                    -----blank
                    <div className=''>
                      <div><Header/></div>
                      {children}
                    </div>
                    -----blank
                  </div>
                  ---3
                </div>
                --2
            </div>
            -1
          </div>
        </main>
      </body>
    </html>
  )
}
